#!/usr/bin/env python3
"""
Porn Site Blocker
Downloads adult-content blocklists and generates a hosts file.
Works on: Rooted Android, Linux, macOS, Windows, Pi-hole, AdGuard Home.
"""

import urllib.request
import re
import sys
import os
import argparse
from pathlib import Path

BLOCKLIST_SOURCES = [
    # Steven Black's adult-only hosts list (curated, ~160k domains)
    "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts",
    # Hagezi's porn blocklist (compact format)
    "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/porn.txt",
    # oisd porn blocklist
    "https://small.oisd.nl/domainswild",
]

REDIRECT_IP = "0.0.0.0"
HOSTS_HEADER = f"""\
# ============================================================
# Porn / Adult Content Blocker - Generated Hosts File
# ============================================================
# Generated by porn_blocker.py
# Redirects adult domains to {REDIRECT_IP} (drops the connection)
#
# How to apply:
#   Android (root):  adb push hosts /etc/hosts
#   Linux/macOS:     sudo cp hosts /etc/hosts
#   Windows:         copy hosts C:\\Windows\\System32\\drivers\\etc\\hosts
#   Pi-hole:         Add as a custom blocklist in Settings > Blocklists
# ============================================================

127.0.0.1 localhost
::1       localhost

"""


def fetch_list(url: str) -> list[str]:
    print(f"  Fetching: {url}")
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "porn-blocker/1.0"})
        with urllib.request.urlopen(req, timeout=30) as resp:
            return resp.read().decode("utf-8", errors="ignore").splitlines()
    except Exception as exc:
        print(f"  WARNING: Could not fetch {url}: {exc}", file=sys.stderr)
        return []


def parse_domain(line: str) -> str | None:
    line = line.strip()
    if not line or line.startswith("#"):
        return None
    # hosts-file format: "0.0.0.0 example.com" or "127.0.0.1 example.com"
    parts = line.split()
    if len(parts) >= 2 and re.match(r"^\d+\.\d+\.\d+\.\d+$", parts[0]):
        domain = parts[1].lower()
    else:
        # plain domain list
        domain = parts[0].lower()

    # Skip localhost / broadcast entries
    if domain in ("localhost", "localhost.localdomain", "broadcasthost", "0.0.0.0"):
        return None
    # Basic domain validation
    if re.match(r"^[a-z0-9][a-z0-9.\-]{1,252}[a-z0-9]$", domain) and "." in domain:
        return domain
    return None


def build_hosts_file(domains: set[str]) -> str:
    lines = [HOSTS_HEADER]
    for domain in sorted(domains):
        lines.append(f"{REDIRECT_IP} {domain}")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate an adult-content blocking hosts file."
    )
    parser.add_argument(
        "-o", "--output",
        default="hosts_porn_blocker",
        help="Output file path (default: hosts_porn_blocker)",
    )
    parser.add_argument(
        "--extra-domains",
        nargs="*",
        metavar="DOMAIN",
        help="Additional domains to block",
    )
    parser.add_argument(
        "--whitelist",
        nargs="*",
        metavar="DOMAIN",
        help="Domains to exclude from the blocklist",
    )
    args = parser.parse_args()

    whitelist = set(d.lower() for d in (args.whitelist or []))
    domains: set[str] = set()

    print("\n[1/3] Downloading blocklists...")
    for url in BLOCKLIST_SOURCES:
        raw_lines = fetch_list(url)
        for line in raw_lines:
            domain = parse_domain(line)
            if domain and domain not in whitelist:
                domains.add(domain)

    if args.extra_domains:
        for d in args.extra_domains:
            domains.add(d.lower())

    print(f"\n[2/3] Collected {len(domains):,} unique domains to block.")

    output_path = Path(args.output)
    output_path.write_text(build_hosts_file(domains), encoding="utf-8")
    print(f"\n[3/3] Written to: {output_path.resolve()}")
    print(f"      File size:  {output_path.stat().st_size / 1024:.1f} KB")

    print("\n--- Deployment Instructions ---")
    print("  Android (requires root via ADB):")
    print(f"    adb push {output_path} /etc/hosts")
    print()
    print("  Android DNS (no root needed):")
    print("    Settings > Network > Private DNS > enter: one.one.one.one")
    print("    Or use the AdGuard / NextDNS app with this list imported.")
    print()
    print("  Linux / macOS:")
    print(f"    sudo cp {output_path} /etc/hosts")
    print()
    print("  Windows:")
    print(f"    copy {output_path} C:\\Windows\\System32\\drivers\\etc\\hosts")
    print()
    print("  Pi-hole / AdGuard Home:")
    print("    Add this file's URL or path as a custom blocklist.")
    print()


if __name__ == "__main__":
    main()
